const fs = require("fs");
const path = require("path");

const root = path.resolve(__dirname, "..");
const plan = fs.readFileSync(path.join(root, "PROJECT_PLAN.md"), "utf8");

const nextTaskMarkers = [
  "- Product maintenance and real-user feedback pass",
  "- Post-launch usability improvements",
  "- First real outbound session feedback",
  "- Second outbound session refinements",
  "- Live outbound run outcomes",
  "- Outcome-driven product fixes",
  "- Improvement queue triage",
  "- Fix queue execution workflow",
  "- Fix queue due-date dashboard",
  "- Fix queue owner workload",
  "- Fix queue owner filter",
  "- Fix queue owner export",
  "- Fix queue CSV export",
  "- Fix queue closeout summary",
  "- Fix queue closeout download",
  "- Fix queue resolved archive",
  "- Fix queue archive restore",
  "- Fix queue archive filtered closeout",
  "- Fix queue filtered closeout download",
  "- Fix queue archive cleanup",
  "- Fix queue archive cleanup export guard",
  "- Fix queue final polish pass",
  "- First real outbound run with archive workflow",
  "- First run packet download",
  "- First run packet JSON export",
  "- First run snapshot history",
  "- First run snapshot export",
  "- Production integration provider setup",
  "- Reviewed production send packet schema",
  "- Reviewed send packet validation preview",
  "- Reviewed send packet audit log",
  "- Reviewed provider dry-run endpoint",
  "- Production send dry-run result history",
  "- Reviewed send retry packet export",
  "- Production send compliance checklist",
  "- Production send release gate summary",
  "- Production provider implementation boundary docs",
  "- Production provider middleware contract",
  "- Production middleware fixture tests",
  "- Production provider local stub",
  "- Production provider stub runbook wiring",
  "- Production provider status-to-stub guidance",
  "- Production provider status export",
  "- Production integration closeout packet",
  "- Production integration final polish",
  "- Production middleware implementation planning",
  "- Production middleware skeleton",
  "- Production middleware skeleton runbook wiring",
  "- Production middleware skeleton status export",
  "- Production middleware adapter guardrails",
  "- Production middleware adapter status docs",
  "- Production middleware audit trail",
  "- Production middleware audit export",
  "- Production middleware replay fixture",
  "- Production middleware replay export",
  "- Production middleware provider adapter checklist",
  "- Production middleware provider adapter checklist export",
  "- Production middleware adapter readiness report",
  "- Production middleware readiness report docs",
  "- Production middleware readiness report export",
  "- Production middleware final provider setup review",
  "- First test-mailbox provider adapter interface",
  "- First test-mailbox provider adapter implementation",
  "- First test-mailbox provider adapter runbook",
  "- First test-mailbox provider adapter replay fixture",
  "- First test-mailbox provider adapter replay docs",
  "- First test-mailbox provider adapter capture audit",
  "- First test-mailbox provider adapter capture endpoint",
  "- First test-mailbox provider adapter capture export",
  "- First test-mailbox provider adapter capture docs",
  "- First test-mailbox provider adapter mismatch fixture",
  "- First test-mailbox provider adapter mismatch docs",
  "- First test-mailbox provider adapter env status",
  "- First test-mailbox provider adapter status docs",
  "- First test-mailbox provider adapter run packet",
  "- First test-mailbox provider adapter run packet docs",
  "- First test-mailbox provider adapter run packet export docs",
  "- First real provider adapter preflight gate",
  "- First real provider adapter preflight docs",
  "- First real provider adapter selection plan",
  "- First real provider adapter selection docs",
  "- First real provider adapter decision record",
  "- First real provider adapter decision docs",
  "- First provider-specific implementation guard",
  "- First provider-specific implementation guard docs",
  "- First Gmail provider adapter implementation skeleton",
  "- First Gmail provider adapter skeleton docs",
  "- First Gmail provider adapter env status export",
  "- First Gmail provider adapter env status docs",
  "- First Gmail reviewed packet preflight",
  "- First Gmail reviewed packet preflight docs",
  "- First Gmail provider audit preview",
  "- First Gmail provider audit preview docs",
  "- First Gmail provider retry preview",
  "- First Gmail provider retry preview docs",
  "- First Gmail provider response mapping preview"
];

const checks = [
  ["plan keeps product goal", plan.includes("## Product Goal")],
  ["plan keeps MVP scope", plan.includes("## MVP Scope")],
  ["plan keeps current status", plan.includes("Current status:")],
  ["plan keeps Ollama direction", plan.includes("AI direction: use local Ollama")],
  ["plan tracks maintenance next", nextTaskMarkers.some((marker) => plan.includes(marker))]
];

const failures = checks.filter(([, passed]) => !passed).map(([label]) => label);
if (failures.length) {
  console.error(`Maintenance project plan test failed: ${failures.join(", ")}`);
  process.exit(1);
}
console.log("Maintenance project plan test passed.");
